apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: mycca-cluster-store
spec:
  provider:
    # Choose one provider and configure. Example: AWS Secrets Manager
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: eso-sa
            namespace: mycca
