replicaCount: 2

image:
  repository: ghcr.io/YOUR_REPO/mycca-api
  tag: latest
  pullPolicy: IfNotPresent

frontendImage:
  repository: ghcr.io/YOUR_REPO/mycca-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

frontendService:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: nginx
  tls:
    enabled: true
    secretName: mycca-tls
    issuer: letsencrypt-prod
  hosts:
    api: api.mycca.local
    frontend: frontend.mycca.local
    grafana: grafana.mycca.local
    keycloak: keycloak.mycca.local

resources: {}


secrets:
  # Use External Secrets Operator (true) or fallback to Kubernetes Secret (false)
  useExternal: true
  name: mycca-secrets

  # Fallback secret data (only used if useExternal=false). Use placeholders.
  fallback:
    KEYCLOAK_CLIENT_SECRET: "changeme"
    SMTP_USERNAME: "changeme"
    SMTP_PASSWORD: "changeme"
    SLACK_WEBHOOK: "https://hooks.slack.com/services/XXX/YYY/ZZZ"
    TEAMS_WEBHOOK: "https://outlook.office.com/webhook/your-teams-webhook-url"
