replicaCount: 1

image:
  repository: ghcr.io/YOUR_REPO/mycca-api
  tag: dev
  pullPolicy: IfNotPresent

frontendImage:
  repository: ghcr.io/YOUR_REPO/mycca-frontend
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

frontendService:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false

resources: {}
